default_platform(:android)

platform :android do

  desc "Lane for distributing app using Firebase App Distributions"
  lane :distribute do
    gradle(task: "clean assembleRelease")
    firebase_app_distribution(
        service_credentials_file: "firebase_credentials.json",
        app: ENV['PRONOTE_FIREBASE_APP_ID'],
        release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
        groups_file: "FirebaseAppDistributionConfig/groups.txt"
    )
  end
end
