name: Test
on:
  push:
    branches: [dev]

jobs:


  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.b64
          base64 -d -i keystore.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >>keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >>keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >>keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >>keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{secrets.ANDROID_KEYSTORE_FILE}}
          KEYSTORE_KEY_ALIAS: ${{secrets.KEYSTORE_KEY_ALIAS}}
          KEYSTORE_KEY_PASSWORD: ${{secrets.KEYSTORE_KEY_PASSWORD}}
          KEYSTORE_STORE_PASSWORD: ${{secrets.KEYSTORE_STORE_PASSWORD}}

      - name: Create Google Services Json file
        run: |
          echo "$GOOGLE_SERVICES" > google-services.b64
          base64 -d -i google-services.b64 > google-services.json
        env:
          GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES_JSON_FILE}}

      # Cache gradle
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cache-${{ runner.os }}-${{ matrix.jdk }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Unit tests
        run: bash ./gradlew test --stacktrace


  instrumentation-test:
    name: Run Instrumentation Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.b64
          base64 -d -i keystore.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >>keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >>keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >>keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >>keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{secrets.ANDROID_KEYSTORE_FILE}}
          KEYSTORE_KEY_ALIAS: ${{secrets.KEYSTORE_KEY_ALIAS}}
          KEYSTORE_KEY_PASSWORD: ${{secrets.KEYSTORE_KEY_PASSWORD}}
          KEYSTORE_STORE_PASSWORD: ${{secrets.KEYSTORE_STORE_PASSWORD}}

      - name: Create Google Services Json file
        run: |
          echo "$GOOGLE_SERVICES" > google-services.b64
          base64 -d -i google-services.b64 > google-services.json
        env:
          GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES_JSON_FILE}}

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          profile: Nexus 6
          avd-name: test
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck


      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports

